trigger:
  branches:
    include:
      - development

parameters:
  - name: environment
    displayName: "Select Environment"
    type: string
    default: dev
    values: [dev, qa, uat, prod]

variables:
- ${{ if eq(parameters.environment, 'dev') }}:
  - group: Opensky-Dev-VariableGroup
  - name: AGENT_POOL
    value: AKS-DEV-Opensky
  - name: K8S_SERVICE_CONNECTION
    value: serviceconnection-dev-opensky

- ${{ if eq(parameters.environment, 'qa') }}:
  - group: Opensky-QA-VariableGroup
  - name: AGENT_POOL
    value: AKS-QA-Opensky
  - name: K8S_SERVICE_CONNECTION
    value: serviceconnection-qa-opensky

- ${{ if eq(parameters.environment, 'uat') }}:
  - group: Opensky-UAT-VariableGroup
  - name: AGENT_POOL
    value: AKS-UAT-Opensky
  - name: K8S_SERVICE_CONNECTION
    value: serviceconnection-uat-opensky
  - name: KEYVAULT_NAME
    value: kvault-cus-uat-opensky


- ${{ if eq(parameters.environment, 'prod') }}:
  - name: AGENT_POOL
    value: AKS-PROD-Opensky
  - name: K8S_SERVICE_CONNECTION
    value: serviceconnection-prod-opensky
  - name: KEYVAULT_NAME
    value: kvault-cus-prod-opensky

- name: IMAGE_NAME
  value: offline-repo

pool:
  name: $(AGENT_POOL)

# ---------- BUILD STAGE ----------
stages:
- stage: Build
  displayName: "Build and Push Docker Image"
  jobs:
  - job: BuildJob
    displayName: BuildJob
    steps:
    - checkout: self
    # CLEAN DOCKER SPACE
    - script: |
        echo "Cleaning Docker disk space..."
        docker system prune -a -f || true
      displayName: "Clean Docker Disk Space"

    # Load Key Vault secrets (UAT / PROD)
    - ${{ if or(eq(parameters.environment, 'uat'), eq(parameters.environment, 'prod')) }}:
      - task: AzureKeyVault@2
        displayName: Load KeyVault secrets (Build)
        inputs:
          azureSubscription: $(K8S_SERVICE_CONNECTION)
          KeyVaultName: $(KEYVAULT_NAME)
          SecretsFilter: |
            ACR-NAME
          RunAsPreJob: true

    - task: AzureCLI@2
      name: BuildImage
      displayName: "Build & Push Image to ACR"
      inputs:
        azureSubscription: $(K8S_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          IMAGE_TAG="$(Build.SourceBranchName)-$(Build.BuildId)"
          IMAGE="$(ACR-NAME).azurecr.io/$(IMAGE_NAME):$IMAGE_TAG"
          
          echo "Generated IMAGE_TAG = $IMAGE_TAG"
          echo "##vso[task.setvariable variable=IMAGE_TAG;isOutput=true]$IMAGE_TAG"


          echo "Logging into ACR..."

          az acr login --name $(ACR-NAME)
          echo "Building Docker image..."

          docker build \
            -f Dockerfile \
            -t "$IMAGE" \
            .

          echo "Pushing Docker image..."
          docker push "$IMAGE"


